### ISSUE TITLE
java.lang.unsopportedOperationException: not supported yet on Jmeter 5.5

### ISSUE THREAD

**Issue by pajdewaal** [toilatester/jmeter-property-reader#1]
When using the plugin on Jmeter 5.5, I'm getting a Warning in the log

```
.
.
.
2022-12-06 17:08:38,410 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2022-12-06 17:08:38,425 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2022-12-06 17:08:38,425 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2022-12-06 17:08:38,428 DEBUG o.a.j.t.ThreadGroup: Ending thread Thread Group 1-1
2022-12-06 17:08:38,428 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-12-06 17:08:38,428 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of PropertyReader@1a4b3ae4
java.lang.UnsupportedOperationException: Not supported yet
    at PropertyReader.testEnded(PropertyReader.java:44) ~[PropertyReader-1.0.0.1.jar:?]
    at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230) ~[ApacheJMeter_core.jar:5.5]
    at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:507) ~[ApacheJMeter_core.jar:5.5]
    at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_301]
2022-12-06 17:08:38,431 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

**Comment by Sumanth1919** [comment]
I am getting same error any turn around for these
